### ISSUE TITLE
IllegalStateException: Must be main thread

### ISSUE THREAD

**Issue by developer--** [InsertKoinIO/koin#1075]
**Describe the bug**
I'm using `Koin 3.0.0-alpha-4 `version and when I'm trying to use injected class from koin then it throws exception 
` KotlinException=kotlin.IllegalStateException: Must be main thread, KotlinExceptionOrigin` 
I have a singleton class where I'm initializing objects using koin like that:
```
@ThreadLocal
object ObjectFactory : KoinComponent{
  val appStateRepository: AppStateRepository by inject()
  val appStateRepositoryDemo =  AppStateRepository()
}
```
 if I use `appStateRepository`  inside background thread (Dispatchers.Default), which is injected by koin, then it throws exception `IllegalStateException: Must be main thread`, but if I use appStateRepositoryDemo than it works fine

Here is a method which  I'm invoking from iOS to inject modules
```
fun initKoinIos(
  userDefaults: NSUserDefaults,
  doOnStartup: () -> Unit
): KoinApplication = initKoin {
  module {
    ...
    single { doOnStartup }
  }
}
```

```
fun initKoin(appDeclaration: KoinAppDeclaration = {}) = startKoin {
  appDeclaration()
  modules(
    platformModule,
    networkModule,
    useCaseModules,
    repositoryModule,
    commonUtils,
  )
}
```

Here is the usage:
```
fun testRepoAccess() {
        ObjFactory.appStateRepository.test() // Ok, here we are in main thread
        CoroutineScope(Dispatchers.Default).launch {
            ObjFactory.appStateRepositoryDemo.test() //  Ok
            ObjFactory.appStateRepository.test() // Not Ok, throws exception (Must be main thread)
        }
}
```

**Expected behavior**
It should work for iOS like it works Android

**Koin project used and used version (please complete the following information):**
`Koin 3.0.0-alpha-4`

**Additional moduleDefinition**
`Coroutines 1.4.2-native-mt`

**UPDATE**
I was using wrong Koin lib name, now I'm using :
`io.insert-koin:koin-core:3.0.1`

and now I have another exception:

`kotlin.native.IncorrectDereferenceException: illegal attempt to access non-shared org.koin.core.context.GlobalContext.KoinInstanceHolder@1c02ca8 from other thread`

**Comment by liauli** [comment]
I also encounter this problem and found the solution. 

Please correct me if I'm wrong, my assumption is that `by inject` will initialize the object lazily, and when the object is needed, it will be created in the `main thread`, but the function that needs it is already in background thread. In K/N, we need to `freeze` the object to make the it accessible by other threads. I don't know how to add `freeze` for the object created in Koin.
Other approach is by making sure the object is created before the function runs in the background thread, Using `get()` instead of `by inject` will do the trick.
