### ISSUE TITLE
Getting duplicate bindings when using getAll()

### ISSUE THREAD

**Issue by kevalpatel2106** [InsertKoinIO/koin#1146]
**Describe the bug**

I tried to use `getAll` to have [multibindings](https://github.com/InsertKoinIO/koin/issues/146). But when I get the list of bindings, the first class in the list always has two instances.

**Sample code:**

```kotlin
import org.koin.core.context.startKoin
import org.koin.dsl.bind
import org.koin.dsl.module
import org.koin.java.KoinJavaComponent.getKoin

interface A
class B : A
class C : A

val koinModule = module {
    factory<B>{ B() } bind A::class
    factory<C>{ C() } bind A::class
}

fun main() {
    startKoin { modules(koinModule) }

    val list  = getKoin().getAll<A>()
    list.forEach { println(it.javaClass.simpleName) }
}
```

I checked this with **koin `3.0.2`** and it worked fine. I got the following output 👇 

```
C
B
```

But when I use **koin `3.1.0`**, I get two instances of class `C`. I got the following output 👇 

```
C
B
C (<- Second instance of class C)
```

**To Reproduce**

1. Run the above code and see the output has duplicate classes

**Expected behavior**

It should have returned one instance f `B` and one instance of `C`. (Just like it was doing in `3.0.2`.

**Koin project used and used version (please complete the following information):**

- `koin-core version 3.1.0`

**Comment by hedvigoscar** [comment]
Still present as of `koin` 3.1.2. Working around with `getAll<T>().distinct()` for now. I tried debugging for a while, but was unable to locate the root cause.

**Comment by kevalpatel2106** [comment]
> Still present as of `koin` 3.1.2. Working around with `getAll<T>().distinct()` for now. I tried debugging for a while, but was unable to locate the root cause.

That's right, my workaround for this one is to use distinct by java class.

```
getAll<T>().toMutableList().distinctBy { it.javaClass }
```

**Comment by hedvigoscar** [comment]
Wouldn't `distinct()` be sufficient? The instances are equal, and calling `distinctBy { it.javaClass }` might filter out some cases where you actually do want multiple instances of the same class (whatever that case might be).

**Comment by wakawaka54** [comment]
This issue is super annoying. Difficult bug to troubleshoot after an upgrade from 2.x to 3.x . Had to change all my `getAll` calls to these extension functions:

```
/**
 * Bug fix workaround for this issue: https://github.com/InsertKoinIO/koin/issues/1146
 */
inline fun <reified R> Koin.getAllDistinct(): List<R> =
    getAll<R>().distinct()

/**
 * Bug fix workaround for this issue: https://github.com/InsertKoinIO/koin/issues/1146
 */
inline fun <reified R> Scope.getAllDistinct(): List<R> =
    getAll<R>(R::class).distinct()
```

**Comment by jacekgajek** [comment]
Still present on 3.1.2

**Comment by jacekgajek** [comment]
Seriously, it's a happy-path unit test which you don't have. Veeery unprofessional...

**Comment by hedvigoscar** [comment]
Kind of odd to speak about unprofessional for open source software that you're not paying for 🤔

**Comment by mohsenoid** [comment]
I also faced it and didn't use it because of this issue. 🤕

**Comment by jonathanarodr** [comment]
I used workaround to fix this similar the suggestions above:
```kotlin
inline fun <reified T : Any> Koin.getAllDistinct(): List<T> {
    return getAll<T>().distinctBy { it.javaClass }
}

inline fun <reified T : Any> Scope.getAllDistinct(): List<T> {
    return getAll<T>().distinctBy { it.javaClass }
}
```

**Comment by nimmortal** [comment]
Hello. 

I was also trapped in this issue. 
My case is more straightforward because I forbid override and Koin complains.

I did small naive research and I conclude that issues are related to the `bind` definition.
In the case when class is registered with the following statement:

```kotlin
single { GlobalService(get()) } bind Service::class
```

Koin creates mapping definitions for both class types: `GlobalService.class` and `Service.class`. 
When `getAll` is called Koin returns the same class twice because:
- there are two mapping records in the registry for the same instance with different class type;
- they both pass filtration in `getAll` method;

https://github.com/InsertKoinIO/koin/blob/336aae60ea2227f08444fe876f761d1482971c4f/core/koin-core/src/commonMain/kotlin/org/koin/core/registry/InstanceRegistry.kt#L148-L152

**Comment by shanio** [comment]
@arnaudgiuliani Will this be addressed? We just discovered it and it caused various hard to spot issues. If I understand the issue correctly, `getAll` returns all bound definitions and last bound definition due to presence in secondaryType -> definition mapping, which is only required for regular get() functionality.

**Comment by arnaudgiuliani** [comment]
Hi there, let me check. I've seen something fixed for the `getAll()` operator lately in 3.1.x, but I can be wrong. Need to check this on 3.1.5 for a fix in 3.1.6.

**Comment by nielsvanvelzen** [comment]
I can confirm this problem still happens in 3.1.5.

**Comment by arnaudgiuliani** [comment]
Yep in progress. Just need to add a `distinct()` step in the result filtering.

Thanks 👍
