### ISSUE TITLE
Upgrading from Koin 2.x

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#1212]
Hello everyone,

we try to help people upgrade to the latest Koin version. First, if you didn't updated it, please use maven central packages of Koin: https://insert-koin.io/docs/migration/maven

From an application in Koin 2.x, we are gathering resources here: https://insert-koin.io/docs/migration/migrate

If you still struggle upgrading your app, let us know:
- open an explicit title and the issue with the `upgrade-issue` label - https://github.com/InsertKoinIO/koin/labels/upgrade-issue
- answer in this thread below.

Since Koin 3.1.3 and more, we have covered many backports. You should be close to what you need.

Cheers.

**Comment by egorikftp** [comment]
https://github.com/InsertKoinIO/koin/issues/1095

**Comment by kkovach** [comment]
I've updated a library that I maintain from Koin 2.X to 3.1.4. We have a user of the library that is using pretty old versions of Gradle (5.4.1), Android Gradle Plugin (3.5.4), Kotlin (1.4.32), and Java (8). They are seeing the following error...

Cannot access 'org.koin.core.component.KoinComponent' which is a supertype of 'my.library.class.Here'. Check your module classpath for missing or conflicting dependencies

I'm able to reproduce this issue with the versions of things that they are using, but I have yet to figure out exactly what the issue actually is. Any help understanding what might be the root cause of this issue would be appreciated. Thanks.

**Comment by arnaudgiuliani** [comment]
ok let me check

**Comment by jokeonmyself** [comment]
https://insert-koin.io/docs/migration/migrate

Page not found
