### ISSUE TITLE
viewModelScope.launch is not work well in Scope ViewModel with version 3.1.3

### ISSUE THREAD

**Issue by PhanVanLinh** [InsertKoinIO/koin#1238]
**Describe the bug**
In version 3.1.2, for getting the ViewModel from a Scope, I use this function
```
fun <T : ViewModel> Scope.getViewModel(
        qualifier: Qualifier? = null,
        state: BundleDefinition? = null,
        owner: ViewModelOwnerDefinition,
        clazz: KClass<T>,
        parameters: ParametersDefinition? = null,
)
```
with a null value for `state: BundleDefinition` and everything working well

After upgrade to 3.1.3, there is no` state: BundleDefinition` in function `getViewModel`. I see that because ViewModelParameter remove the `initialState: Bundle? = null` so I remove the null value for `state: BundleDefinition`

However, in a Fragment that use the ViewModel from scope, after I open, close and reopen it few times, the ViewModel won't update anymore. At the first time I open the Fragment, everything working well but after I close and reopen, it face the issue like
```
fun doSomething() {
      // code can reach here
      viewModelScope.launch {
             // code can not reach here
      }
}
```
**Koin project used and used version**
 koin-core: 3.1.3
 koin-android: 3.1.3

**Comment by StanislavChumarin** [comment]
Still reproducible on koin 3.1.4

**Comment by octa-one** [comment]
This issue can relate to 1240 https://github.com/InsertKoinIO/koin/issues/1240
Example:
ViewModel is scoped in scope(named("SomeScope")), than the Fragment uses this ViewModel. Fragment destroyed -> Fragment of ViewModelStore destroyed -> ViewModel::onClear is called -> viewModelScope is closed after onClear -> ViewModel is reused in another Fragment because SomeScope stays alive, but viewModelScope is already closed.

**Comment by thadcodes** [comment]
FYI a workaround to this issue is posted in #1240.  You have to declare your scoped view models at `factory` instead of `viewModel` even though you continue to use them as view model on the inject side
