### ISSUE TITLE
[Question] Issue upgrading to Koin 3.2

### ISSUE THREAD

**Issue by alejandro-rios** [InsertKoinIO/koin#1369]
**Describe the bug**
Hello :wave:,  I've try to migrate from Koin 3.1.5 to 3.2.0, I've changed some declarations in our modules from `single { }` to `singleOf()` and from `viewModel { }` to `viewModelOf()` but after clean and run the app I'm getting this error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;
        at com.metamap.sdk_components.di.AppModuleKt.<clinit>(AppModule.kt:26)
        at com.metamap.sdk_components.di.AppModuleKt.getApplicationModule(AppModule.kt:26)
        at com.metamap.metamap_sdk.SdkStartUpProvider.<init>(SdkStartUpProvider.kt:25)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6380)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.dsl.ModuleKt" on path:...`

any idea of what am I missing? I think it may be something missing from the documentation, but I'm not sure.

**To Reproduce**
1. In my case I have modules with both `single { }`, `singleOf()` and others with `viewModel { }`, `viewModelOf()`

**Expected behavior**
It should work with both declarations

**Koin project used and used version (please complete the following information):**
First it was:  `koin-android 3.1.5` - `koin-core 3.1.5`
Now: `koin-android 3.2.0`

There's another *weird thing*, doc says that I can do this:

![image](https://user-images.githubusercontent.com/10689052/175425327-ac099393-74d1-45d2-a72c-ea2df4936883.png)

but when i did it i get this:

![image](https://user-images.githubusercontent.com/10689052/175425362-62aa3fed-95e0-4a01-a517-fe4ebcf7c99e.png)

This is the class definition:

![Screen Shot 2022-06-23 at 17 27 31](https://user-images.githubusercontent.com/10689052/175425473-c3ce6fef-55c4-4bd3-9738-f67a4b577d39.png)

**Comment by alejandro-rios** [comment]
I have this imports in the project:
![Screen Shot 2022-06-28 at 10 46 23](https://user-images.githubusercontent.com/10689052/176223422-e1b537d2-8ca9-4c2a-819a-d3dd6e7f8294.png)
![Screen Shot 2022-06-28 at 10 46 33](https://user-images.githubusercontent.com/10689052/176223436-e517d9a6-ed81-43bf-b192-a77495746c87.png)
![Screen Shot 2022-06-28 at 10 46 39](https://user-images.githubusercontent.com/10689052/176223456-be389492-e957-427e-a614-8a8ddd07c20a.png)

**Comment by SteliosPapamichail** [comment]
Stumbled into the same issue as well, haven't found a solution yet.

**Comment by StephanSchuster** [comment]
Same here. Do not get it to work without lambdas as said in docs. I always need to use curly braces.

**Comment by arnaudgiuliani** [comment]
don't you have something that lock your Koin version down? be sure to be able to import the `singleOf` or any constructor DSL extension.

**Comment by alejandro-rios** [comment]
Update: Digging a little more into the project I found that one of the libraries we use depends on `Koin` version `3.1.5`, I tested without this library and the project worked again without the strange error message.

For that I've use `./gradlew app:dependencies` command and search/trace `Koin` in the results:
![Screen Shot 2022-07-18 at 15 04 10](https://user-images.githubusercontent.com/10689052/179607752-db216eca-0bc1-4064-a7a8-259488a2def4.png)

However, the error of using `bind()` without the `{ }` persists. but I guess is something related with the last comment of @arnaudgiuliani.

**Comment by arnaudgiuliani** [comment]
interesting. Is it an internal library or public one?

**Comment by alejandro-rios** [comment]
Is a library called [Mati](https://github.com/GetMetaMap/metamap-android-sdk)

**Comment by viktor-savchik-idf** [comment]
I've faced with the same issue

**Comment by victsomie** [comment]
I too am facing the same error while using [Mati](https://github.com/GetMetaMap/metamap-android-sdk)

**Comment by victsomie** [comment]
> Is a library called [Mati](https://github.com/GetMetaMap/metamap-android-sdk)

Did you find a solution for your case? I am stuck at this

**Comment by withoutclass** [comment]
I've discovered through my testing that Koin Modules created with Koin 3.1 are not forwards-compatible with Koin 3.2.  This means any and all Koin Modules created with Koin 3.1 must be upgraded to Koin 3.2 at the same time.  This is going to result in having to rebuild and re-publish 10-15 artifacts for my team to do what should be a backwards compatible update, sigh.

**Comment by insiderser** [comment]
@withoutclass Don't worry. Upgrading 3.2->3.3 was not forward-compatible as well for me :) And my internal feeling tells me that there will be more binary-incompatible releases to come.

**Comment by arnaudgiuliani** [comment]
I tried to ask people to help with inventory of upgrades issues. Could you list your issues? I would like to help going in a smoother path.

**Comment by insiderser** [comment]
@arnaudgiuliani For me, the main issue with Koin is how it keeps binary and behavior backwards compatibility.

https://zsmb.co/maintaining-compatibility-in-kotlin-libraries/

We work on an Android library that uses Koin to manage its internal dependencies. We create our own KoinApplication instance that contains all our modules (https://insert-koin.io/docs/reference/koin-core/context-isolation). Our library uses Koin v3.1

Now imagine a client app, that integrates our Android library, uses Koin already. And they use Koin v3.3. But our library uses Koin v3.1.

![Untitled Diagram](https://user-images.githubusercontent.com/34242332/227798874-c1560d1d-3a9b-4be8-a885-cdfc20d23af4.png)

Normally, this wouldn't cause any issues, as long as binary API compatibility is preserved between versions. It's normal that libraries get compiled against older libraries, and client apps use newer versions of those dependent libraries.

But it's not the case with Koin, since it doesn't keep binary and behavior compatibility between minor releases (3.1 -> 3.2 -> 3.3). This issue's description contains an example of binary compatibility not being kept.

But personally I noticed one case where Koin doesn't keep behavior compatibility: when Koin calls `createEagerInstances()` on custom KoinApplication instances. In Koin v3.1, `createEagerInstances()` wasn't invoked by Koin at all. Koin didn't create eager instances. You had to call `createEagerInstances()` manually each time you create a KoinApplication. This allowed Koin clients to call `createEagerInstances()` later after the KoinApplication instance is retrieved.

But some later release (don't remember which one, maybe v3.2) changed that behavior. Now `createEagerInstances()` gets called during KoinApplication creation automatically. And now suddenly our client code that functionally depends on eager instances being created after the KoinApplication instance gets created, stopped working. Now, what are we supposed to do? Urgently create a new library hotfix release to address the behavior change in Koin? Force all customers to use an older Koin version that doesn't has this change? That's not the way to go.

As for the tools to help with that:
1. Binary compatibility validator: https://github.com/Kotlin/binary-compatibility-validator
2. Behavior compatibility: creating functional tests

**Comment by arnaudgiuliani** [comment]
@insiderser in your case the context is more complex. I can help make some patch to help upgrade. 

For 3.5, I've added API check & propose to add the following `koinApplication` function, in order to let you control eager instance creation:

```kotlin
fun koinApplication(createEagerInstances : Boolean = true, appDeclaration: KoinAppDeclaration? = null): KoinApplication {
    val koinApplication = KoinApplication.init()
    appDeclaration?.invoke(koinApplication)
    if (createEagerInstances) {
        koinApplication.createEagerInstances()
    }
    return koinApplication
}
```

Please remind that open source projects are community driven, and this is important to gather feedback as possible 🙏 
Thanks for your feedback.

If you have any other upgrade issue, please reach the team 👌

**Comment by insiderser** [comment]
> For 3.5, I've added API check & propose to add the following `koinApplication` function, in order to let you control eager instance creation:
> 
> ```kotlin
> fun koinApplication(createEagerInstances : Boolean = true, appDeclaration: KoinAppDeclaration? = null): KoinApplication {
>     val koinApplication = KoinApplication.init()
>     appDeclaration?.invoke(koinApplication)
>     if (createEagerInstances) {
>         koinApplication.createEagerInstances()
>     }
>     return koinApplication
> }
> ```
> 
> currently in [bbd18de](https://github.com/InsertKoinIO/koin/commit/bbd18decab33a8879d2b4443d760dafcbb668780).

@arnaudgiuliani This caused yet another incompatibility that suddenly there is no method with signature `org.koin.core.KoinApplication org.koin.dsl.KoinApplicationKt.koinApplication(kotlin.jvm.functions.Function1)`, causing a `java.lang.NoSuchMethodError` crash for the SDK I work on.

No need to resolve this issue now. Just wanted you to be aware of this.

**Comment by arnaudgiuliani** [comment]
I'm interested in the details about the API imcompatibility, thanks. The new `koinApplication` offers default values to let you the function as wish
