### ISSUE TITLE
Using the new ViewModel Generic api Koin 3.3 for android, causes warning

### ISSUE THREAD

**Issue by aytajde** [InsertKoinIO/koin#1481]
**Describe the bug**
Migrating koin version to 3.3 and using the new ViewModel Generic api causes warning
**To Reproduce**
We upgraded the Koin version to 3.3 for android. And we are using the generic viewModel api like below in our BaseFragment:

```
abstract class BaseFragment<State, Effect, ViewModel : BaseViewModel<State, Effect>, B : ViewBinding> :
    Fragment(), LifecycleOwner {
    protected abstract val vmClazz: KClass<VM>
    val viewModel: VM by viewModelForClass(clazz = vmClazz) { parametersOf(arguments) }
```
the `vmClazz` property causes the warning saying: Accessing non-final property vmClazz in constructor. 
But we can't make this property final as we are inheriting it from different fragments.

Can someone give a clear example on how to use the new Koin ViewModel Generic api's below methods?
```
ComponentActivity.viewModelForClass(
    clazz: KClass<T>,
    qualifier: Qualifier? = null,
    owner: ViewModelStoreOwner = this,
    state: BundleDefinition? = null,
    key: String? = null,
    parameters: ParametersDefinition? = null,
): Lazy<T>
```

```
fun <T : ViewModel> getLazyViewModelForClass(
    clazz: KClass<T>,
    owner: ViewModelStoreOwner,
    scope: Scope = GlobalContext.get().scopeRegistry.rootScope,
    qualifier: Qualifier? = null,
    state: BundleDefinition? = null,
    key: String? = null,
    parameters: ParametersDefinition? = null,
): Lazy<T>
```
                                                                                                      
**Koin project used and used version (please complete the following information):**
 upgraded from `const val koin = "3.2.0-beta-1` to
  ```
  const val koin_core = "3.2.2"
    const val koin_android_version = "3.3.0"
```

**Comment by dongnh311** [comment]
Koin have 3 function write on file org.koin.androidx.viewmodel.ext.android
You can import this to use.

**Comment by Nek-12** [comment]
First of all, this warning is there for a reason. Imagine what happens when you override your property clazz in the child view model? the clazz property of **base class** will be passed to the viewmodel! I don't think your code will work at all. You shouldn't really inject your viewmodel this way. Just override the viewmodel field as it was supposed to be. 

The warning stems from a fundamental issue of using Base classes for your viewmodels and classes. This is an antipattern for the exact same reason you're facing now. Because overridden properties in child classes are initialized **after** base class properties are, you won't get the behavior you initially intended. 

The nasty workaround (NOT a solution) would be to make the vm field `lazy` but this would only mask the issue, forcing the warning to go away (as soon as you access viewmodel too early it will explode). But since `by viewModelForClass` is already a lazy function, wrapping it in another lazy would be another anti-pattern. I suggest you get rid of your base classes and choose another approach like interface delegation or property delegation (use composition, avoid inheritance)
