### ISSUE TITLE
How to unit test in Kotlin Multiplatform when it needs context ?

### ISSUE THREAD

**Issue by Egi10** [InsertKoinIO/koin#1532]
I have a class like below:

```
// Android
actual class Test(privat val context: Context)

// ios
actual class Test

// shared
expect class Test
```

When I try to run a unit test like this :

```
class CheckModuleTest: KoinTest {

    @Test
    fun `verify koin app`() {
        koinApplication {
            modules(
                module
            )
            checkModules()
        }
    }
}

```
I had a failure like this:

`Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'android.content.Context' q:''. Check your definitions!`

**Comment by johnmarcus015** [comment]
You can't use the koinApplication direct for tests. Instead of it, create a rule like below:  
```kotlin
@get:Rule
val koinTestRule = KoinTestRule.create {
    // Your KoinApplication instance here
    modules(myModule)
}
```
When you need to call specific modules, you can mock dependencies using mockk library. 
The rule and the mocks are explained in the documentation. The reference link is:
[Koin in unit tests - Documentation](https://insert-koin.io/docs/reference/koin-test/testing/#junit-rules)

**Comment by Egi10** [comment]
thanks, my issue was resolved with this documentation: https://insert-koin.io/docs/reference/koin-test/checkmodules

```
@Test
    fun `verify all module`() {
        appSharedModule.verify(
            extraTypes = listOf(
                Context::class,
                io.ktor.client.HttpClientConfig::class,
                io.ktor.client.engine.HttpClientEngine::class
            )
        )
    }
```
