### ISSUE TITLE
Definitions with more than 10 constructor parameters with new constructor DSL

### ISSUE THREAD

**Issue by aliyevakhalida** [InsertKoinIO/koin#1585]
**Is your feature request related to a problem? Please describe.**
We decided to migrate from the old DSL to the new concise one. But while migrating we faced a limitation of the new version. While giving the definitions inside the module we realized that the DSL does not support definitions for components with more than 10 constructor parameters.

**Describe the solution you'd like**
Right now we have quite a few components that take more than 10 constructor parameters. We would like to use the new constructor DSL for defining those as well.

**Describe alternatives you've considered**
As an alternative we have kept the old DSL for those components.

**Target Koin project**
[core-3.2.2](https://github.com/InsertKoinIO/koin/releases/tag/core-3.3.3)
[android-3.3.0](https://github.com/InsertKoinIO/koin/releases/tag/android-3.3.3)

**Comment by aytajde** [comment]
Maybe they didn't implement the varargs approach because of the Generics limitation of varargs as the type is being cleared on compile time. 
Java implements generics using type erasure, which means that type information is not available at **runtime**. When you use varargs with generic types, the type information for the generic type parameter is erased. 
This means that the compiler cannot determine the actual type of the elements in the varargs parameter at runtime. Instead, the compiler treats the varargs parameter as an array of the raw type.

**Comment by aliyevakhalida** [comment]
The problem has been solved in the new version
