### ISSUE TITLE
Kotlin multiplatfrom compose Desktop. Error in dmg

### ISSUE THREAD

**Issue by nekzabirov** [InsertKoinIO/koin#1639]
After building dmg and running app from DMG, I got error Could not instance of Factor [*], but from executor it is working

**Comment by arnaudgiuliani** [comment]
any more details?

**Comment by akelix** [comment]
The same issue.

Kotlin multiplatform application with compose desktop.
Kotlin 1.9.0
AndroidXCompose 1.5.1

Use koin as DI. Trying versions 3.5.1 / 3.5.2-RC1.
Application working on linux, on Windows, on Android.
On MAC working only JAR. DMG is falling on start with message:
"Could not create instance for '[Singleton: my class]"
Fails on first injected instance. I has only singleton instances in DI.

**Comment by akelix** [comment]
Found the problem.

I have also used File based Sqllite adapter. On DMG build your app running on read-only file system.
That is why it is crashed on initialization and it looks like koin issue.

Steps to find out real problem:
 - mount dmg
 - Using terminal open mounted volume in /Volumes/{your App}
 - Launch your application with executable in  /Volumes/{your App}/ directory
 - Logs will show you real problem.


I think issue could be closed, because it is not koin issue.

**Comment by arnaudgiuliani** [comment]
Yeah, more related to Compose Desktop issue error. thanks

**Comment by EnosSalar** [comment]
I have the same problem, can you please tell me how to fix it?

**Comment by lydavid** [comment]
I was able to solve this with https://github.com/lydavid/MusicSearch/issues/974#issuecomment-2348131376.
