### ISSUE TITLE
Breaking Changes for scoped view model in version 3.5.3

### ISSUE THREAD

**Issue by Ucash** [InsertKoinIO/koin#1750]
**Describe the bug**
Using activity scope, the koinNavViewModel method creates a new view model each time if the default key and qualifier arguments are used. As a workaround I had to add a key argument.

**Initial investigation**
I have found that org.koin.androidx.viewmodel.resolveViewModel method internally use new getViewModelKey method which builds view model key based on provided key, qualifier and id of a scope if it is not the root one. In the result when key and qualifier are left default (both are nulls) the same key is generated for each view model and ViewModelProvider calls factory each time view model type is not matched.

Is this intentional change that from 3.5.3 for scoped view model key or qualifier argument is required?

**Comment by will-nolan** [comment]
We're also seeing the same behaviour. Scoped viewmodels injected via Koin are now giving multiple instances whereas previously the same instance across the scope was expected. Invocation below.

```
val viewModelFoo : Foo = koinViewModel(
        scope = getKoin().getScope(FOO_SCOPE)
        )
```

**Comment by dees91** [comment]
I observe similar erroneous behavior:
```kotlin
scope<ParentActivity> {
        factory { SomeDependency(get()) } 
        viewModelOf(::FragmentXViewModel)
        viewModelOf(::FragmentYViewModel)
}
```
In 3.5.0, `FragmentXViewModel` and `FragmentYViewModel` received the same `SomeDependency` instance within the `ParentActivity` scope - for example, in the situation of a transition from fragment X to fragment Y within the same `ParentActivity` launch.  In 3.5.3 they get different instances of `SomeDependency` in the described situation.

**Comment by dees91** [comment]
@congvc-apero You are right that in this simplified snippet it doesn't prove anything, that's why I prepared a repo with example that view models get the same instance of `SomeDependency` within the `ParentActivity` scope in 3.5.0 and they get a different instance in 3.5.3:
https://github.com/dees91/koinexperiment/tree/main/app/src/main/java/pl/deesoft/koinexperiment/experiment

| 3.5.0 | 3.5.3 |
| ------ | ------ |
|![Screenshot_1705479803](https://github.com/InsertKoinIO/koin/assets/1900691/94477c4d-815e-4c3e-a0bf-55535005f441)| ![Screenshot_1705479822](https://github.com/InsertKoinIO/koin/assets/1900691/02c3bd61-9d51-4ffe-a82b-33ec1317acaf)|

**Comment by dees91** [comment]
@congvc-apero Thank you for your reply. The `scoped` dsl may be applicable in my case.
However, referring to
> broke your code, but in a good way

I would like to determine:
- whether the change in factory behavior in this case is an intentional fix for erroneous Koin behavior in previous versions (factory in this exact case returned the same instance for sure in Koin versions 3.4.3 and 3.5.0 and probably in earlier versions as well)
- or the change in the behavior of factory in this case in version 3.5.3 is an accidental regression

This is important because I would like to know whether the behavior from previous versions in this situation will return in Koin 3.5.4 or this is the expected behavior.

**Comment by volkert-fastned** [comment]
Interesting how there are multiple behavioral/breaking changes going from 3.5.1 to 3.5.3. See also this issue I reported last month: https://github.com/InsertKoinIO/koin/issues/1738

A patch-level version update should not have breaking changes.

**Comment by arnaudgiuliani** [comment]
>I would like to determine:
> whether the change in factory behavior in this case is an intentional fix for erroneous Koin behavior in previous versions (factory in this exact case returned the same instance for sure in Koin versions 3.4.3 and 3.5.0 and probably in earlier versions as well)
or the change in the behavior of factory in this case in version 3.5.3 is an accidental regression

Here it's more a regression due to VM key build refactoring. IF I have proper tests/examples to reproduce to add to examples app, I can quickly patch it. Sorry for the break 🙏

**Comment by arnaudgiuliani** [comment]
Fixed. See PR. Let's check 3.5.4-RC1
