### ISSUE TITLE
Online documentation links are broken

### ISSUE THREAD

**Issue by NinoDLC** [InsertKoinIO/koin#1767]
**Describe the bug**
Online documentation links are broken

**To Reproduce**
* On https://insert-koin.io/docs/setup/koin/, click on any "INFO From now you can continue on Koin Tutorials to learn about using Koin: xxx" (like https://insert-koin.io/docs/setup/quickstart/kotlin)
* Get a 404

**Expected behavior**
Not a 404

**Comment by geoffreylgv** [comment]
Hi @NinoDLC, no link is broken there though
Please, @arnaudgiuliani @marcellogalhardo @pedrofsn, can you confirm ?

**Comment by NinoDLC** [comment]
I guess I must be clicking stuff incorrectly then 😁
https://github.com/InsertKoinIO/koin/assets/11870220/a123eef5-f631-46ab-9256-d01c9aae5a98

**Comment by geoffreylgv** [comment]
> I guess I must be clicking stuff incorrectly then 😁 https://github.com/InsertKoinIO/koin/assets/11870220/a123eef5-f631-46ab-9256-d01c9aae5a98

> [!IMPORTANT]
> I got it @NinoDLC, but it seems like someway it's correct and returning the expected page, and in another way it returns 404

**Check these videos**

_200 oK_

https://github.com/InsertKoinIO/koin/assets/52314615/65a46527-239c-4af9-952a-27fc14d23159

_404 not Found_

https://github.com/InsertKoinIO/koin/assets/52314615/32e52fd6-7e7b-44ea-bbc8-e13c32fb5117

**Comment by arnaudgiuliani** [comment]
did you tried refreshing this setup page? Seems all link got to tutorials section.

**Comment by geoffreylgv** [comment]
> did you tried refreshing this setup page? Seems all link got to tutorials section. Perhaps a cache problem? 🤔

Yes @arnaudgiuliani, I refreshed the setup page several times; and also, it's not a cache problem

When I take a look at the doc the `koin` file

It's 404, even on the GitHub repo, 

![image](https://github.com/InsertKoinIO/koin/assets/52314615/2d2b099a-55df-4598-91a8-d35eef6a7d1a)

There is no place you can find the page referenced

**Comment by NinoDLC** [comment]
Yes, even refreshing, using a different browser (Firefox),using incognito mode... same issue.

**Comment by arnaudgiuliani** [comment]
Go on `https://insert-koin.io/docs/setup/koin`, click again on `setup` in the menu. And you can click on the links to follow tutorials.

But agree, there is something wrong in the lings 🤔

**Comment by arnaudgiuliani** [comment]
it's located here: https://github.com/InsertKoinIO/koin-getting-started/tree/main/docs
perhaps website is out of sync? 🤔

**Comment by geoffreylgv** [comment]
> it's located here: https://github.com/InsertKoinIO/koin-getting-started/tree/main/docs perhaps website is out of sync? 🤔

Alright, I see; this means it's called from another repo.
What do you think if I add the direct link (Absolute paths) instead of the relative one that is there actually?

**`Example`**

---
title: Koin
---

All you need to setup Koin in your project

## Current Versions

You can find all Koin packages on [maven central](https://search.maven.org/search?q=io.insert-koin).

Here are the currently available versions:

| Project   |      Version      |
|----------|:-------------:|
| koin-core |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-core)](https://mvnrepository.com/artifact/io.insert-koin/koin-core) |
| koin-core-coroutines |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-core-coroutines)](https://mvnrepository.com/artifact/io.insert-koin/koin-core-coroutines) |
| koin-test |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-test)](https://mvnrepository.com/artifact/io.insert-koin/koin-test) |
| koin-android |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-android)](https://mvnrepository.com/artifact/io.insert-koin/koin-android) |
| koin-android-test |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-android-test)](https://mvnrepository.com/artifact/io.insert-koin/koin-android-test) |
| koin-android-compat |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-android-compat)](https://mvnrepository.com/artifact/io.insert-koin/koin-android-compat) |
| koin-androidx-navigation |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-androidx-navigation)](https://mvnrepository.com/artifact/io.insert-koin/koin-androidx-navigation) |
| koin-androidx-workmanager |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-androidx-workmanager)](https://mvnrepository.com/artifact/io.insert-koin/koin-androidx-workmanager) |
| koin-compose |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-compose)](https://mvnrepository.com/artifact/io.insert-koin/koin-compose) |
| koin-androidx-compose |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-androidx-compose)](https://mvnrepository.com/artifact/io.insert-koin/koin-androidx-compose) |
| koin-androidx-compose-navigation |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-androidx-compose-navigation)](https://mvnrepository.com/artifact/io.insert-koin/koin-androidx-compose-navigation) |
| koin-ktor |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-ktor)](https://mvnrepository.com/artifact/io.insert-koin/koin-ktor) |
| koin-logger-slf4j |  [![Maven Central](https://img.shields.io/maven-central/v/io.insert-koin/koin-logger-slf4j)](https://mvnrepository.com/artifact/io.insert-koin/koin-logger-slf4j) |

## Gradle Setup

### Kotlin

Starting from 3.5.0 you can use BOM-version to manage all Koin library versions. When using the BOM in your app, you don't need to add any version to the Koin library dependencies themselves. When you update the BOM version, all the libraries that you're using are automatically updated to their new versions.

Add `koin-bom` BOM and `koin-core` dependency to your application: 
```kotlin
implementation(platform("io.insert-koin:koin-bom:$koin_version"))
implementation("io.insert-koin:koin-core")
```
If you are using version catalogs:
```toml
[versions]
koin-bom = "x.x.x"
...

[libraries]
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "di-koin" }
koin-core = { module = "io.insert-koin:koin-core" }
...
```
```kotlin
dependencies {
    implementation(libs.koin.bom)
    implementation(libs.koin.core)
}
```

Or use an old way of specifying the exact dependency version for Koin:
```kotlin
dependencies {
    implementation("io.insert-koin:koin-core:$koin_version")
}
```

You are now ready to start Koin:

```kotlin
fun main() {
    startKoin {
        modules(...)
    }
}
```

If you need testing capacity:

```groovy
dependencies {
    // Koin Test features
    testImplementation("io.insert-koin:koin-test:$koin_version")
    // Koin for JUnit 4
    testImplementation("io.insert-koin:koin-test-junit4:$koin_version")
    // Koin for JUnit 5
    testImplementation("io.insert-koin:koin-test-junit5:$koin_version")
}
```

:::info
From now you can continue on Koin Tutorials to learn about using Koin: [Kotlin App Tutorial](https://github.com/InsertKoinIO/koin-getting-started/blob/main/docs/quickstart/kotlin.md)
:::

### **Android**
