### ISSUE TITLE
Kotlin Native Support

### ISSUE THREAD

**Issue by amrboxit4me** [InsertKoinIO/koin#244]
Is your feature request related to a problem? 

- I just wonder if this library will support Kotlin Native in the future or not?

 Thanks a lot

**Comment by arnaudgiuliani** [comment]
Hello,

@zsmb13 has already made a good work about Kotlin Native version: https://github.com/InsertKoinIO/koin/issues/120

This will be possible if we have enough users for this kind of feature, because this clearly structuring. We have to take away form some JVM types that we use in core. 

But why not :)

**Comment by Wavesonics** [comment]
This would be awesome

**Comment by rickpms** [comment]
Is anyone working on this yet? If not, I can help.

**Comment by zsmb13** [comment]
I believe the module plan I laid out in the related issue for JS will no longer work with the current multiplatform project model, as it now seems to force using multiple source sets in a single module rather than a module per target. I'm not sure if the old structure can still be used, my impression was that it can't be.

(I also don't have time to work on this anymore, unfortunately, at least in the foreseeable future.)

**Comment by arnaudgiuliani** [comment]
I have to close firstly Koin 2.0 before launching Koin MPP. Soon a 2.0-RC 👍

**Comment by arnaudgiuliani** [comment]
@zsmb13 do you have time to check against Koin v2 architecture? There is some use of jvm hashet/hashmap to speedup the compoment lookup. Architecture components has been also reduced in this way also.

**Comment by zsmb13** [comment]
I'd love to help, but I won't be able to look at it for a while. If there's someone else to take it on, feel free to go ahead, I unfortunately can't promise a timeframe for my involvement.

**Comment by arnaudgiuliani** [comment]
sure no problem :)

I'll take time to look at it in a moment.

**Comment by JavierSegoviaCordoba** [comment]
Any update about this?

**Comment by arnaudgiuliani** [comment]
Kotlin native support will be one of the next big features for Koin 👍 
Will begin to work on it in a moment. Would like to push some alpha about it end of summer/september
 depending on my avilability.

**Comment by arnaudgiuliani** [comment]
WIP for Koin 3.0.0

**Comment by slipdef** [comment]
What is ETA for Koin 3.0 tho?

**Comment by arnaudgiuliani** [comment]
for now, don't know sorry. Need to push many fix/improve on 2.1.x.
Can be interesting to shoot the first alpha, to help test and improve perfs.
