### ISSUE TITLE
Injecting Objects within Activity tests

### ISSUE THREAD

**Issue by LukasAnda** [InsertKoinIO/koin#326]
**Describe the bug**
After I upgraded to Androidx, my Koin test which injects repository to modify the response, the test failed, although it worked before. Now it creates wrong version of Repository and returns null to my flowable, more on this thing [https://stackoverflow.com/questions/54040468/koin-testing-on-androidx-with-activity](here)

**To Reproduce**
1. copy the repository mentioned in the post
2. run instrumented test
3. see it fail

**Expected behavior**
The test should work, because prior to upgrade, everything worked fine and the test passed

**Koin project used and used version (please complete the following information):**
 1.0.2

**Additional moduleDefinition**
none

**Comment by jamireh** [comment]
I went ahead and took a look at this. From what I can see, the issue resides in the fact that `declareMock()` isn't functioning as you would expect for a `factory` dependency.

If you follow the source of `declareMock()` to `declareMockedDefinition()`, you'll see that it searches for the dependency definition, creates a copy, and then overrides it with a `Mockito` mock. However, in your case, your `BuffarooRepository` is a `factory` so each time a dependent accesses it from the Koin graph, it will receive a brand new mock. So the instance you access in your `BrowseActivityTest` is different than the one that's accessed in the `GetBufferoos` class during the test. Only the instance in `BrowseActivityTest` has the mocked method; the instance in `GetBufferoos` class during the test has no mocked definitions and that's why it's returning `null`.

Your test acquires one instance of the `BuffarooRepository` and mocks a single method in `stubBufferooRepositoryGetBufferoos()`. The problem here is that this mutation is never accessed by the code under test; if the module definition was a `single` instead of a `factory`, then your mutation of this instance would be present during the actual test.

As for the fix, you would need to change the `BufferooRepository` definition to be a `single`  instead of a `factory`. However, that would mean that `declareMock()` was never supposed to work with `factory` and I think that's considered a bug. 

The `declareMock()` method accepts a `stubbing` lambda with the definition `(T.() -> Unit)` such that you can setup your mock in this lambda and it would be applied to the mock. The bug is that this lambda is not invoked within the definition, it's only applied to the mock that's returned from `declareMock()`. The `stubbing` parameter needs to be passed down to `declareMockedDefinition()` and applied within definition so that it's invoked each time the definition is accessed – such as when the definition is a `factory`.

**Comment by arnaudgiuliani** [comment]
fixed in 2.0.0-beta2
