### ISSUE TITLE
koin-android-viewmodel does not work!

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [InsertKoinIO/koin#391]
it shows error, I am angry!!

**Comment by Orgmir** [comment]
Thanks for opening an issue, you need to be more specific about what your problem is. It will really help the maintainers of the project if you could provide us with:

- The errors you are getting
- Versions of the libraries you are using
- Steps to replicate the problem

An extra mile would also be to provide an example project where the error happens.

**Comment by EdwardvanRaak** [comment]
@Orgmir 

I only started playing with this lib today (so I'm not that angry :smile:) but with these dependencies:

```
implementation 'org.koin:koin-android:2.0.0-beta-1'
implementation 'org.koin:koin-androidx-viewmodel:1.0.1'
```

You get an unresolved reference on `viewModel`

![viewmodel](https://user-images.githubusercontent.com/1560465/54130506-cb26e480-4410-11e9-8c4b-12f3b8ee2d59.png)

This is not a problem with `implementation 'org.koin:koin-android:1.0.2'`

**Comment by NurseyitTursunkulov** [comment]
than you should explicitly write that we must use only this dependencies!

**Comment by EdwardvanRaak** [comment]
> implementation 'org.koin:koin-android:2.0.0-beta-1' implementation 'org.koin:koin-androidx-viewmodel:1.0.1'

For the 2.0.0 beta you should use 
```
implementation 'org.koin:koin-android:2.0.0-beta-1'
implementation 'org.koin:koin-androidx-viewmodel:2.0.0-beta-1'
```

The wiki page already mentions `2.0.0-beta-1` but the docs still default to `1.0.2` which have different dependencies. So yeah, pretty silly but that is probably why docs should be up to date.
