### ISSUE TITLE
module(appModule) tell me the argument is mistake

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [InsertKoinIO/koin#416]
`val appModule = listOf(viewModelModule, remoteModule, localModule, repoModule)`
`val viewModelModule = listOf(loginModule)`
`val loginModule = module {
    single<SimpleText> { SimpleText.from(getProperty("login_rich_content")) }
    single { LoginViewModel() }
}`
remoteModule、localModule、repoModule has nothing!!!!!

then I invoke 
`
startKoin {
            androidLogger()
            androidContext(this@App)
            Log.e(this.toString(),appModule::class.java.name)
            modules(appModule)
}
`

then I have this error : None of the following functions can be called with the arguments supplied:

I  try this：
```
// loginModule  not viewModelModule
val appModule = listOf(loginModule, remoteModule, localModule, repoModule)

```

that is ok,but why the previous is error。I saw the log , the appModule's  class name is the same every time。
class name ：java.util.Arrays$ArrayList

**Comment by erickok** [comment]
`val viewModelModule = listOf(loginModule)` is a list of modules already, so when you do `val appModule = listOf(viewModelModule, remoteModule, localModule, repoModule)` the type inference will create a list of `Any` instead of a list of modules. Use `val appModule = listOf(loginModule, remoteModule, localModule, repoModule)` instead or, depending on what you want to do, you can use `val appModule = viewModelModule + listOf(remoteModule, localModule, repoModule)`

**Comment by zhuangYuFeiHelloGit** [comment]
> `val viewModelModule = listOf(loginModule)` is a list of modules already, so when you do `val appModule = listOf(viewModelModule, remoteModule, localModule, repoModule)` the type inference will create a list of `Any` instead of a list of modules. Use `val appModule = listOf(loginModule, remoteModule, localModule, repoModule)` instead or, depending on what you want to do, you can use `val appModule = viewModelModule + listOf(remoteModule, localModule, repoModule)`

thank u  very much! It work, and I get it.
