### ISSUE TITLE
Still no support for scoped ViewModels?

### ISSUE THREAD

**Issue by mahmed1987** [InsertKoinIO/koin#468]
As I understand when we create a module like this 
`module {
    // single instance of HelloRepository
    single<HelloRepository> { HelloRepositoryImpl() }

    // Simple Presenter Factory
    factory { MySimplePresenter(get()) }

    // Simple Java Presenter
    factory { MyJavaPresenter(get()) }

    // scope for MyScopeActivity
    scope(named<MyScopeActivity>()) {
        // scoped MyScopePresenter instance
        scoped { MyScopePresenter(get()) }
    }

    // MyViewModel ViewModel
    viewModel { MyViewModel(get()) }

    //scoped viewmodel
    
}` 
the viewmodels we declare go and attach themselves to the activity.

In a single activity application that means all the viewmodels would be alive all the time and their "oncleared" will not be called. This is a leak .

What I am referring to is Scoped ViewModels. This is a necessary feature and would love to hear some official explanation from the Koin team.

Thanks

**Comment by erikhuizinga** [comment]
If the last `FragmentActivity` or `Fragment` the `ViewModel` belongs to is destroyed, then `ViewModel#onCleared` is called.

Koin doesn't store `ViewModel` _instances_ in memory if created with the `viewModel { ... }` function. Instead, it just stores _how to instantiate it_ using a factory ([`viewModel { ... }` is a `factory { ... }`](https://github.com/InsertKoinIO/koin/blob/f78eeafa03f06f2fa6351d5fb09d327c52e8d626/koin-projects/koin-android-viewmodel/src/main/java/org/koin/android/viewmodel/dsl/ModuleExt.kt#L42)) and [lets the `ViewModelStore` of the `LifecycleOwner` store it](https://github.com/InsertKoinIO/koin/blob/f78eeafa03f06f2fa6351d5fb09d327c52e8d626/koin-projects/koin-android-viewmodel/src/main/java/org/koin/android/viewmodel/ViewModelResolution.kt#L19-L26).

The `ViewModelStore` is where `ViewModel` instances are stored normally (if you use `ViewModelProviders#of` and `ViewModelProvider#get` instead of Koin). The Android framework takes care of clearing the `ViewModel` from memory after `onCleared` is called.

There used to be scoped `ViewModel` instances, but with the current implementation where they are stored in the `ViewModelStore` of a `LifecycleOwner` they are scoped by the Android framework. If you really need to use a scope with a `ViewModel` (which you shouldn't need), take a look at [this Gist](https://gist.github.com/erikhuizinga/031058b7781c64d4752f4e6d69c3ad9a).

@ggajews: any additions?

**Comment by arnaudgiuliani** [comment]
In 2.0.x, You can define a ViewModel inside a scope use its visibility with that.
