### ISSUE TITLE
ViewModel with Activity as a Parameter doesn't work when rotation screen

### ISSUE THREAD

**Issue by geandelon** [InsertKoinIO/koin#579]
**Describe the bug**
My Activity ProgramaListaActivity uses viewmodel with injection parameters. As you can see below:
`
class ProgramaListaActivity : BaseListaMvpActivity(), ProgramaLista.View {
    override fun obterPresenterPrincipal() = programasPresenter
    private val programasPresenter: ProgramaListaPresenter by viewModel { parametersOf(this) }
}
`

My viewModel's ProgramaListaPresenter class:
`class ProgramaListaPresenter(
    private val programaRepository: ProgramaRepository,
    private val view: ProgramaLista.View
) : BaseMvpPresenter(), ProgramaLista.Presenter {
}`

And my module:
`val viewModelModule = module {
    // ProgramaLista
    viewModel { (view: ProgramaLista.View) -> ProgramaListaPresenter(get(), view) }
 }`
 
So, when I rotate my phone, the view variable keeps the reference of the last activity. We know that when rotate the phone the activity is destroy and then recreate.
My problem is when I use the view variable in my ViewModel class (ProgramaListaPresenter) after the phone rotation, my activity doesn't get update. 
I could see that the hashCode of the view variable keeps the same but the activity hashCode has been changed as you can see below.

1. - ProgamaListaActivity: VIEW na activity: 138081958
2. - ProgramaListaPresenter$este: VIEW no Presenter: 138081958
3. - ProgramaListaActivity: VIEW na activity: 237568804
4. - ProgramaListaPresenter$este: VIEW no Presenter: 138081958
5. - ProgramaListaActivity: VIEW na activity: 232280099
6. - ProgramaListaPresenter$este: VIEW no Presenter: 138081958

Can you help me with this?

Thanks

**Comment by wax911** [comment]
Just a suggestion, you already pointed out that your view doesn't get update after a configuration change, which is not surprising. The view model state/instance tends to be retained in the view model factory to avoid recreation of it when being created from the same context, which is why VM can survive configuration changes, if I recall correctly this is more of an Android Impl :thinking:

So the issue from what I can tell is you're expecting the parameter to passed every time there is a configuration change or activity/fragment recreation 

Perhaps you should avoid passing objects that are bound to activities/fragment lifecycle to your view model and rather separate that functionality into a presenter. I'd suggest making use of Live Data if you can to observer VM changes from your activity.
