### ISSUE TITLE
CreatedAtStart behavior

### ISSUE THREAD

**Issue by lionel-dangelo** [InsertKoinIO/koin#608]
Hello,

I try to use the createdAtStart option to instanciate a service (by passing the android context in parameter) on startup of my app.
MyService1 has a default constructor "init"

```
val serviceModule = module {
single(createdAtStart = true) { MyService1(androidContext()) }    
single { MyService2() }  
single { MyService3() }
}
```

In this example, i saw in debug mode that the init of MyService1 is called only after Koin has loaded all modules (so init of MyService 1 is called after the MyService3 is loaded. Is this a correct behavior or a bug ?

The only way I found to force the init called ealier is : 

```
val serviceModule = module {
val myService1 = MyService1(MyApplication.instance.applicationContext)
single(createdAtStart = true) { myService1 }    
single(createdAtStart = true) { MyService2() }  
single(createdAtStart = true) { MyService3() }
}
```

But I'm not sure it's a good workaround and I can't use the koin androidContext()
Some advice for that ?

Thank you,

**Comment by PedroMoniz** [comment]
I am also having issues with createdAtStart and how it should work.

`
single(createdAtStart = true) {
        Room.databaseBuilder(
            get(),
            CountryDatabase::class.java,
            "country_database"
        ).addCallback(object : RoomDatabase.Callback() {
            override fun onCreate(db: SupportSQLiteDatabase) {
                super.onCreate(db)
                val countryDB: CountryDatabase by inject()
                GlobalScope.launch(IO){
                   ...
                   }
                }
            }
        }
        ).build()
    }
    single(createdAtStart = true) { get<CountryDatabase>().countryDao() }
`

The onCreate triggers when I use the database but then it is too late because I need to do some background work with it. 

I have tried several ways and I just do not understand what createEagerInstances() or createAtStart is actually supposed to do.

**Comment by aosa4054** [comment]
@lionel-dangelo 
It seems to that instances declared as `createAtStart = true` are created in `starKoin()` function, not in `module { ... }`. Your solution, create instance before `single { ... }`, looks works well. Koin stores lambda to create instance and invoke and do create when `get<T>()` firstly called (called in `startKoin()` if you use `createAtStart = true`) so that your solution `single(createdAtStart = true) { myService1 }` let Koin store the lambda ((Unit) -> myService1). The instance you create and the instance Koin stores after `startKoin()` will be same. 
Koin androidContext() is not available out of the scope like `single { ... }`.

@PedroMoniz 
Now, the instance  of CountryDatabase you use in callback for Room and declare in `single{ ... }` might be different. So please write `single(createdAtStart = true) { get<CountryDatabase>().countryDao() }` before `single(createdAtStart = true) { Room.databaseBuilder( ... ).build()}`. It may be fixed. 
```
single(createdAtStart = true) { get<CountryDatabase>().countryDao() }
single(createdAtStart = true) {
    Room.databaseBuilder((),
        CountryDatabase::class.java,
        "country_database"
    ).addCallback(object : RoomDatabase.Callback() {
        override fun onCreate(db: SupportSQLiteDatabase) {
            super.onCreate(db)
            val countryDB: CountryDatabase by inject()
            GlobalScope.launch(IO){
               ...
               }
            }
        }
    }
    ).build()
}
```

**Comment by PedroMoniz** [comment]
It does not work. The callback is not called on the start.

Currently I am doing a dummy call to the db just to force the db initialization on my splash screen when the app starts. I really do not like this workaround.

Before the callback I also tried the createFromAsset method with the room databasebuilder. It may not have worked due to the same problem of createdAtStart not actually doing anything (at least it looks like it).

**Comment by iliaskomp** [comment]
I also assumed that the `createdAtStart` flag initializes that object before everything the other ones. However, as mentioned above, that is not the case. Is this a bug or intended behavior? 

In my case, the solution of @lionel-dangelo is not applicable. I cannot instantiate the object outside of `single` because it needs koin dependencies.
