### ISSUE TITLE
SharedViewModel injection via Constructor

### ISSUE THREAD

**Issue by leungandrew** [InsertKoinIO/koin#739]
In the spirit of unit testing, it is much easier to use constructor injection than field injection as you can simply pass a mock object through the constructor instead of setting up Koin and test modules.

For that reason, all my fragment's dependencies are injected by constructor.  However, it appears that when you inject a viewModel to a fragment via `get()`, it'll always create a new instance.  And from the docs, the way to get a share view model is to use the `by sharedViewModel()` extension within the fragment, but that means it must be injected by field.

I am using a single activity application.

Is there a way that I can resolve a dependency for a viewModel that is resolved using `sharedViewModel()` by constructor in a module?

For example:
```
module {
  fragment { MyFragment(get()) }
  viewModel( MyViewModel() }
}
```
where `MyFragment(val viewModel: MyViewModel)`

It'd be great to be able to do something like:
```
module {
  fragment { MyFragment(getSharedViewModel()) } // something like this
  viewModel( MyViewModel() }
}
```
and it'll reuse the activity's view model of `MyViewModel`

**Comment by Nekromancer** [comment]
I'm not sure if that's possible. ViewModel is tightly bound to lifecycle of activity/fragment

**Comment by leungandrew** [comment]
It's tightly bound to the lifecycle of an activity yes (that is if you are using the shared scope).  And since it's being injected into a fragment, that means it is part of some activity, so the reference to the view model should exist. 

Currently, if you use the `get()` extension, it'll simply create a new instance for you.  If there's a way to have an extension for `getSharedViewModel()` or `getGraphViewModel()` where it'll pull from a shared scope if it exists, then we'll be able to inject from constructor.  Maybe there's some sort of delay or chicken and egg problem where a Fragment needs to exist before it can get the activity (or NavGraph), but if we're injecting via a FragmentFactory, then likely it means there's some activity reference already (or if using a NavHostFragment) which can be used as the scope.

**Comment by simpers** [comment]
This is exactly what I would currently need. I'm trying to use a Fragment and its ViewModel in two different cases, where the first one this Fragment is on its own to do something, and upon completion will pop, and the other case it is part of a 3-step process where it is step number two. So in this latter case I want the parent PagerFragment that instantiates this Fragment to inject a SharedViewModel into its own ViewModel and this subfragment, so that they can communicate about the overall state. The case is inviting people to a group. It can be done by inviting people to an existing group as well as when the group is being created (optional step 2, for instance). 

This basically means that the inner ViewModel just does what it does whether it is part of a nested state or not, but I cannot inject a shared instance of it in the PagerFragment case unless I somehow hack it by "fishing it" from the fragment instead, or something.

And if this pattern is not a great one, how would I code a Fragment to be reusable in this case? 🤔

**Comment by arnaudgiuliani** [comment]
Not sure the Android API could allow that. Need investigation here, to know if we have enough context via constructor
