### ISSUE TITLE
stateViewModel(bundle = intent.extras) can't be used at all?

### ISSUE THREAD

**Issue by elye** [InsertKoinIO/koin#787]
**To Reproduce**
Koin version: `2.1.5`

When using Koin to inject ViewModel with savedStateHandle as below, all works well.
```
private val viewModel : MyViewModel by stateViewModel()
```
However, if I wanted to pass in the intent.extra, it crashes complaining the intent is null.
```
private val viewModel : MyViewModel by stateViewModel(bundle = intent.extras)
```

This is not ideal, meaning whenever we have `bundle` to pass in, we can't use `stateViewModel`.

We have to workaround using
```
private val viewModel by lazy {
    getStateViewModel<MyViewModel> (bundle = intent.extras)
}
```

Refer to below for more info
https://stackoverflow.com/questions/61224797/stateviewmodel-injection-on-koin-crash-when-sending-intent-extra-parameter

**Comment by arnaudgiuliani** [comment]
Fixed in 2.1.6

**Comment by mehmetdelikaya** [comment]
Does it work on 3.0.1 as well?

**Comment by arnaudgiuliani** [comment]
yes, should be in 3.0.1

**Comment by mehmetdelikaya** [comment]
@arnaudgiuliani Hi there,
I just decided to upgrade from version 2.1.5 to version 3.2.0. I couldn't find a way to use getStateViewModel with intent extras or fragment arguments . Below snippets are indicating how I used to use it with 2.1.5. Could you indicate how i should be using it with 3.2.0?

```
val viewModel: T by lazy {
        getStateViewModel(viewModelClass(),bundle = intent.extras)
}
```

and this is how i get viewModelClass()

```
private fun viewModelClass(): KClass<T> {
        return ((javaClass.genericSuperclass as ParameterizedType)
            .actualTypeArguments[0] as Class<T>).kotlin
}
```

**Comment by arnaudgiuliani** [comment]
is this API could help?

![image](https://user-images.githubusercontent.com/2360688/119460879-6b8e2880-bd3f-11eb-8888-135556b4abde.png)

**Comment by mehmetdelikaya** [comment]
Hi @arnaudgiuliani 
Thanks for your reply. I have tried it and here is my findings.

I used to have the ViewModel when module declaration like below, 
``` 
viewModel { (handle: SavedStateHandle) -> SomeViewModel(handle, androidApplication(),get()) } 
``` 

I have changed my viewModel declaration in my base activity as follows regarding to your indicated api. (Also it would be good if state parameter was nullable as intent.extra might be null sometimes)
```
val viewModel: T by stateViewModel(state = { intent.extras!! }, clazz = viewModelClass())
```

And I got crash when running app saying that `Can't get injected parameter #0 from DefinitionParameters[] for type 'androidx.lifecycle.SavedStateHandle'`.  

And then I have found your article on [medium](https://medium.com/koin-developers/whats-next-with-koin-2-2-3-0-releases-6c5464ae5e3d) that this type of view model declarations won't work anymore. That's why I have  decided to change my viewModel declaration as follows.

``` 
viewModel { SomeViewModel(androidApplication(),get()) } 
``` 

I have changed the way I was passing fragment arguments and intent extra too, so the following works for me in my base activity now.

```
val viewModel: T by stateViewModel(clazz = viewModelClass())
```

Feel free to give feedback if you think there is misusage.
Thanks
