### ISSUE TITLE
checkModules within instrumentation test

### ISSUE THREAD

**Issue by Yamko** [InsertKoinIO/koin#804]
Is there any way to run `checkModules` within Instrumentation test? 

I'm getting the error "No tests were found". I've already checked that #241 . But unfortunately, mocking is not an option in my case. Also I don't have Robolectric in my project.

**Comment by erickok** [comment]
"No tests were found" means that Gradle doesn't even find your test to execute. Do you have any Instrumentation (Espresso) tests at all that run? Did you set upo the test runner? First try to create an androidTest and your see that checkModules will run too.

**Comment by niom** [comment]
Difficult to say anything exact because there's so little to start with.

But based on that my best guess is that you might be using JUnit5 and have not configured gradle properly.

```
// This will only help if you are using JUnit5
test {
    useJUnitPlatform()
}
```  

My second guess would be that for some reason the naming of the tests is not done in that way that gradle would find them when it's scanning files for tests. Usually using keywords like: *Test.kt or *Spec.kt.
