### ISSUE TITLE
[QUESTION] How to checkModules with Scoped using getSource??

### ISSUE THREAD

**Issue by nschwermann** [InsertKoinIO/koin#864]
checkModules will always fail with any scope which provides a scoped instance with getSource. Is there a proper way to provide a source in checkModules?

example:

```
val myModule = module {
   
   scope<User> {
          scoped{ DependencyNeedingUser(getSource()) }
   }
}
```

And in the test:
```
    @Test
    fun `check my module`(){
        startKoin {
            modules(myModule)
        }.checkModules()
        stopKoin()
    }
```

Will always fail because getSource returns null. How do I provide a source for a checkModule test?

**Comment by Pfoerd** [comment]
I have seen the current implementation based on TypeQualifier, which would not be suitable for some cases we have in our Android applications with Koin.

We have to create several different scopes with the same source, which - of course - have different scope qualifiers, which cannot be the TypeQualifier of the source type, because it would be ambiguous. In this case we would need an option to provide the source types for #checkModules as a configuration (like the existing solution for parameters). 

Is it planned to support such cases? Or is the way we use scope sources not as Koin intends?
