### ISSUE TITLE
No definition found for class Dynamic Feature Module

### ISSUE THREAD

**Issue by overhound** [InsertKoinIO/koin#888]
**Describe the bug**
Trying to access the `viewModel` instance from a fragment within a `ViewPager` that is in a dynamic feature module produces `org.koin.core.error.NoBeanDefFoundException: No definition found for class:'so.so.class'. Check your definitions!`

**To Reproduce**
Easiest way to reproduce this is with a `ViewPager`
1. Declare `viewModel` in a Fragment in the `ViewPager` with `by viewModel()`
2. Try to access `viewModel` in either `setMenuVisibility` or `onHiddenChanged` (in the case that the`Fragment` is visible/not hidden)
3. See error

**Expected behavior**
If a call is made to access the `viewModel` then the definition should be available. Especially if made after after `onCreate` or `onAttach` has been called.

**Koin project used and used version:**
`koin-core version 2.1.6`

**Additional moduleDefinition**
My`ViewPager`'s parent is a `Fragment`. Both(along with module definitions) are defined in a dynamic feature module. So, the module definitions are injected when this parent `Fragment` is attached, and unloaded when detached.

**Comment by egorikftp** [comment]
Hello, in my project I also have a Dynamic feature.
Due to when the app starting we need to register all koin modules and call `startKoin` method, we are not able to initiate dynamic feature dependencies.

In this case you need to call `loadKoinModules` in `init` block of your fragment and call `unloadKoinModules` on `onDestroy`.

Please follow the source code: 

https://github.com/egorikftp/Lady-happy-Android/blob/e1575cad67c1d1fa440eaa8da5653e7312efe112/sources/dynamicFeature/postCreator/src/main/java/com/egoriku/ladyhappy/postcreator/presentation/fragment/PostCreatorFragment.kt#L42

**Comment by overhound** [comment]
Yes this is exactly what I am doing. I should have written that as well. `loadKoinModules` is called in the init method. However Im calling `unloadKoinModules` in the `onDetach` since that is the last point in the lifecycle. Still Im facing this issue.

**Comment by egorikftp** [comment]
@overhound Could you please reproduce on sample project?

**Comment by overhound** [comment]
Just to update this. 

I was lazy loading the modules initially like this

`    private val loadFeatures by lazy { loadKoinModules(modules) }`
` private fun injectModule() = loadFeatures`

Loading the modules directly as mentioned i.e
`    init {
        loadKoinModules(modules)
    }`
instead of:
`    init {
        injectModule()
    }`
appears to have fixed it. I don't have a lot of time atm to properly debug this and produce a full report.
