### ISSUE TITLE
What is difference between androidContext() and inject our context from activity or fragment ?(Can we inject activity context like this?)

### ISSUE THREAD

**Issue by miladsalimiiii** [InsertKoinIO/koin#898]
### **First** approach for inject context  : 
Suppose that we have module like this :

```
val utilModule = module {
     factory { MyClass(androidContext()) }
}
```

Our class is : 

```
class MyClass(private val context: Context){

        fun myFun(){
               //Use context here 
               }
}
```

### **Second** approach is : 

Suppose that we have module like this :

```
val utilModule = module {
     factory { MyClass() }
}
```

Our class is : 

```
class MyClass(){

        fun myFun(context:Context){
               //Use context here 
               }
}
```

Then we can pass `context` from `activity` :  

```
class MainActivity : BaseActivity(){
  private val mMyClass: MyClass by inject()
  mMyClass.myFun(requireContext())
}
```

My question is what is difference between 2 approach ??

**Comment by rocca23** [comment]
You should generally avoid keeping strong references to a Context that is not an Application's Context, because this is a common source of memory leaks. The second approach, where `context`is a local variable rather than a member variable is always preferrable, so you don't retain the Context instance.

There are circumstances where it's ok to keep a strong reference the the Context, for example if MyClass's instance is never going to outlive the Activity's instance (that is, MyClass is a composite class: Activity "owns" it). If you are sure about this, you can declare MyClass with a `factory`declaration (never `single`) with a deconstructed argument:
```kotlin
val utilModule = module {
     factory { (activityContext: Context) ->
        MyClass(activityContext) 
     }
}
```
and inject it like this:
```kotlin
class MainActivity : BaseActivity(){
  private val mMyClass: MyClass by inject { parametersOf(this) }
}
```
Be sure to use myClass only after onCreate, when Activity is a valid Context.

Again, however, I would suggest the 2nd approach.

**Comment by miladsalimiiii** [comment]
> You should generally avoid keeping strong references to a Context that is not an Application's Context, because this is a common source of memory leaks. The second approach, where `context`is a local variable rather than a member variable is always preferrable, so you don't retain the Context instance.
> 
> There are circumstances where it's ok to keep a strong reference to the Context, for example if MyClass's instance is never going to outlive the Activity's instance (that is, MyClass is a composite class: Activity "owns" it). If you are sure about this, you can declare MyClass with a `factory`declaration (never `single`) with a deconstructed argument:
> 
> ```kotlin
> val utilModule = module {
>      factory { (activityContext: Context) ->
>         MyClass(activityContext) 
>      }
> }
> ```
> 
> and inject it like this:
> 
> ```kotlin
> class MainActivity : BaseActivity(){
>   private val mMyClass: MyClass by inject { parametersOf(this) }
> }
> ```
> 
> Be sure to use myClass only after onCreate, when Activity is a valid Context.
> 
> Again, however, I would suggest the 2nd approach.

**Thanks for your reply but did you read this :**  

https://android-developers.googleblog.com/2009/01/avoiding-memory-leaks.html

**Comment by rocca23** [comment]
> **Thanks for your reply but did you read this ?**
> 
> https://android-developers.googleblog.com/2009/01/avoiding-memory-leaks.html

The article you linked says (in other words) exactly what I said...

> avoid escaping the context outside of its own scope

and
> use the Application context

What I also added, is that these rules are not unconditioned; if you know what you are doing, you can hold a strong reference to an Activity. If your MyClass, that holds the strong reference, is itself strong-referenced *only* inside the Activity, then you can take for granted that it will be garbage-collected together with the Activity, causing no leak.

This again *only if you know what you are doing*, thus I still suggest to
> avoid escaping the context outside of its own scope 

(your second approach mentioned in the OP).

**Comment by techyourchance** [comment]
Given Koin introduced the concept of `AndroidScopeComponent` and `activityScope()` (which, as far as I can tell, is tied to Activity's lifecycle), it would make a lot of sense to make a reference to Activity object available for services injected from within the respective "activity scope". This is a very common pattern when using manual dependency injection, Dagger and Hilt.

In fact, in Hilt, you automatically get access to the enclosing Activity object inside ActivityComponent (or child components).

I think this statement is too broad to be correct:

> You should generally avoid keeping strong references to a Context that is not an Application's Context, because this is a common source of memory leaks. The second approach, where `context`is a local variable rather than a member variable is always preferrable, so you don't retain the Context instance.

It's indeed the case that improper management of Context references is a common source of memory leaks, but it doesn't mean that we should "avoid keeping strong references to a Context that is not an Application's Context" or that "The second approach, where `context`is a local variable rather than a member variable is always preferrable". In fact, the second approach is actually rarely ever preferrable.

Fundamentally, what @rocca23 suggested if developers would want to inject Activity context into constructors is to use assisted injection. I think that this approach exposes the implementation details of the services to their clients (MyActivity knows that MyClass uses Context internally), and will also lead to unnecessary code duplication.

So, is the information provided in this thread still relevant for Koin 3.x, or, maybe, there is a way to "add" Activity reference into e.g. `activityScope()`?

**Comment by arnaudgiuliani** [comment]
Hello There,

> So, is the information provided in this thread still relevant for Koin 3.x, or, maybe, there is a way to "add" Activity reference into e.g. activityScope()?

when you use an Activity or Fragment Scope in Koin, you can resolve the "source" of the scope.  This mean that you can resolve your Activity or Fragment for the given scope, which seems ok as everything will be destroyed for this scope once it's closed.
You can check: https://insert-koin.io/docs/reference/koin-android/scope#using-android-scopes

Exposing the source is only available for Activity & Fragment. From my personal point of view, I avoid being dependent of the Android SDK. But seems that we ne need such usecase in DI, as you can see it in Dagger Hilt Codelabs for example.
